# Generated by Django 5.0.14 on 2026-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Canonical meters — see apps.core.units. Optional; only used to compute BMI alongside a logged body weight.', max_digits=8, null=True),
        ),
    ]
