# Generated by Django 5.0.14 on 2026-08-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_bmi',
            field=models.BooleanField(default=True, help_text="Whether the dashboard's BMI card is shown at all — independent of whether height/weight exist to compute it, so a user who'd rather not see the figure can turn it off outright."),
        ),
    ]
