# Generated by Django 5.0.14 on 2026-08-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_show_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Suomi'), ('sv', 'Svenska'), ('ru', 'Русский'), ('it', 'Italiano'), ('et', 'Eesti')], default='en', max_length=10),
        ),
    ]
