# Generated by Django 5.0.14 on 2026-08-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_achievements',
            field=models.BooleanField(default=True, help_text="Whether the dashboard's achievements carousel (longest streak, workout count, PRs, total volume — see apps.analytics.achievements) is shown at all — same independent-of-whether-there's-anything-to-show opt-out as show_bmi, for a user who'd rather not see it."),
        ),
    ]
