# Generated by Django 5.0.14 on 2026-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_show_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_achievements',
            field=models.BooleanField(default=True, help_text="A privacy setting, not a display one: the dashboard's achievements carousel (longest streak, workout count, PRs, total volume — see apps.analytics.achievements) is shared across every user on this instance, so this controls whether *this* user's own achievements are included in what everyone sees, not whether they personally see the carousel at all."),
        ),
    ]
