# Generated by Django 5.0.14 on 2026-08-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_show_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_achievements',
            field=models.BooleanField(default=True, help_text='A privacy setting, not a display one: the dashboard\'s achievements carousel (longest streak, workout count, PRs, total volume) and "Recently active" list (last time this user started a workout — see apps.analytics.achievements) are both shared across every user on this instance, so this controls whether *this* user\'s own data is included in what everyone sees, not whether they personally see either widget at all.'),
        ),
    ]
