# Generated by Django 5.0.14 on 2026-08-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_show_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_name_to_others',
            field=models.BooleanField(default=True, help_text="A second, more granular privacy setting than show_achievements: whether other users on this instance ever see this user's first name (see public_display_name()) — the username itself is always shown regardless, since it was already visible everywhere show_achievements applies before this field existed. Off falls back to the username alone."),
        ),
    ]
