# Generated by Django 6.1 on 2026-08-15 20:03

from django.db import migrations, models


def backfill_existing_users_as_onboarded(apps, schema_editor):
    """Every account that already exists at the point this migration
    runs was, by definition, created before the onboarding prompt
    existed — there's nothing to ask a returning user that a "welcome"
    modal is meant for. Only accounts created *after* this migration
    (via the model's own default=False) should ever see it."""
    User = apps.get_model("accounts", "User")
    User.objects.update(onboarding_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sitedisclaimer_user_totp_enabled_user_totp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            backfill_existing_users_as_onboarded, migrations.RunPython.noop
        ),
    ]
