# Generated by Django 6.1 on 2026-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sso_user',
            field=models.BooleanField(default=False),
        ),
    ]
