# Generated by Django 6.1 on 2026-08-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_sso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_gravatar',
            field=models.BooleanField(default=False),
        ),
    ]
