# Generated by Django 6.1 on 2026-08-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_show_gravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_friend_requests',
            field=models.BooleanField(default=True, help_text="Off stops other users on this instance from sending you a friend request at all. Doesn't affect friend requests you already have, or friendships you already made."),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_group_invites',
            field=models.BooleanField(default=True, help_text='Off stops a group member from inviting you to a group directly. You can still join any group yourself using its invite link, if you have one.'),
        ),
    ]
