# Generated by Django 6.1.1 on 2026-09-09 18:45

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_allow_friend_requests_user_allow_group_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=apps.accounts.models.EncryptedTextField(blank=True, default=''),
        ),
    ]
