# Generated by Django 6.1 on 2026-09-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='body_tracking_reminders_enabled',
            field=models.BooleanField(default=True, help_text="Shows a dashboard card nudging you to log a body measurement when you haven't logged one in a while. Turn off to never see that reminder."),
        ),
    ]
