# Generated by Django 6.1.1 on 2026-09-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_body_tracking_reminders_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appearance',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('auto', 'Auto (match device)')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('nordic', 'Nordic'), ('vaporwave', 'Vaporwave'), ('earth', 'Earth'), ('zen', 'Zen')], default='default', max_length=20),
        ),
    ]
