# Generated by Django 6.1.1 on 2026-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_appearance_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nutrition_enabled',
            field=models.BooleanField(default=True, help_text="Shows nutrition (food diary, recipes, diet plans) in navigation and on the dashboard. Turn off to hide it if you don't want to track nutrition — existing nutrition data is never deleted, and its pages stay reachable directly by a link."),
        ),
    ]
