# Generated by Django 6.1.1 on 2026-09-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_nutrition_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepting_new_clients',
            field=models.BooleanField(default=True, help_text='Off stops new coaching requests from reaching you. Existing coaching relationships, and any request you already received, are unaffected.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_personal_trainer',
            field=models.BooleanField(default=False, help_text="Lets you build gym programs and diet plans other users can request you coach them on. Turning this off doesn't end any coaching relationship you already have."),
        ),
    ]
