# Generated by Django 6.1 on 2026-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_accepting_new_clients_user_is_personal_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stretching_enabled',
            field=models.BooleanField(default=True, help_text='Shows stretching (routines, guided sessions) in navigation and suggests a cool-down after a workout. Turn off to hide it — existing stretching data is never deleted.'),
        ),
    ]
