# Generated by Django 5.0.14 on 2026-08-14 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_api_keys_per_user', models.PositiveIntegerField(default=10, help_text='How many API keys a single user may have active at once.')),
            ],
        ),
        migrations.CreateModel(
            name='RateLimitTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('requests_per_minute', models.PositiveIntegerField(default=60)),
                ('requests_per_day', models.PositiveIntegerField(default=5000)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['requests_per_minute'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A label to tell your keys apart — not shown to anyone else.', max_length=100)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='api.ratelimittier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiKeyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('profile', 'Profile'), ('exercises', 'Exercises'), ('programs', 'Programs'), ('workouts', 'Workouts'), ('measurements', 'Measurements'), ('activities', 'Activities'), ('records', 'Records'), ('analytics', 'Analytics')], max_length=20)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.apikey')),
            ],
            options={
                'ordering': ['api_key_id', 'context'],
            },
        ),
        migrations.AddConstraint(
            model_name='apikeypermission',
            constraint=models.UniqueConstraint(fields=('api_key', 'context'), name='unique_api_key_context'),
        ),
    ]
