# Generated by Django 6.1 on 2026-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apikeypermission_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeypermission',
            name='context',
            field=models.CharField(choices=[('profile', 'Profile'), ('exercises', 'Exercises'), ('programs', 'Programs'), ('workouts', 'Workouts'), ('measurements', 'Measurements'), ('activities', 'Activities'), ('records', 'Records'), ('analytics', 'Analytics'), ('nutrition', 'Nutrition'), ('stretching', 'Stretching')], max_length=20),
        ),
    ]
