# Generated by Django 6.1 on 2026-08-16 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('target_calories', models.PositiveIntegerField()),
                ('target_protein_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('target_carbohydrate_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('target_fat_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('serving_unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('piece', 'piece')], max_length=10)),
                ('calories', models.PositiveIntegerField()),
                ('protein_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrate_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fiber_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sugar_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('saturated_fat_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodium_mg', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null for the built-in default meal slots.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_meal_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DietPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calories', models.PositiveIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.dietplan')),
                ('meal_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nutrition.mealslot')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_type', models.CharField(choices=[('fat_loss_aggressive', 'Fat loss — aggressive'), ('fat_loss_moderate', 'Fat loss — moderate'), ('fat_loss_conservative', 'Fat loss — conservative'), ('maintenance', 'Maintenance'), ('muscle_gain_lean', 'Muscle gain — lean bulk'), ('muscle_gain_moderate', 'Muscle gain — moderate bulk'), ('muscle_gain_aggressive', 'Muscle gain — aggressive bulk')], max_length=25)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('target_rate_kg_per_week', models.DecimalField(decimal_places=3, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='dietplan',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_plans', to='nutrition.nutritiongoal'),
        ),
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biological_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(help_text='Stored instead of a raw age, so it never goes stale.')),
                ('activity_job', models.CharField(choices=[('sedentary', 'Desk job, mostly sitting'), ('light', 'On my feet some of the day'), ('moderate', 'On my feet most of the day'), ('physical', 'Physically demanding / manual labor')], max_length=10)),
                ('daily_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('training_sessions_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('training_session_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('other_exercise_minutes_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('active', 'Active'), ('very_active', 'Very active')], max_length=15)),
                ('self_reported_daily_calories', models.PositiveIntegerField(blank=True, help_text="If you already track this, tell us — used only to compare against this app's own estimate, never as an input to it.", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_calories', models.PositiveIntegerField()),
                ('protein_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrate_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source', models.CharField(choices=[('calculated', 'Calculated from goal'), ('manual', 'Set manually'), ('adjusted', 'Accepted a suggested adjustment')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='nutrition.nutritiongoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('servings', models.PositiveSmallIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DietPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('diet_plan_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.dietplanmeal')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nutrition.food')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nutrition.recipe')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diary_entries', to='nutrition.food')),
                ('meal_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nutrition.mealslot')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diary_entries', to='nutrition.recipe')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nutrition.food')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='nutrition.recipe')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mealslot',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='unique_system_meal_slot_name'),
        ),
        migrations.AddConstraint(
            model_name='mealslot',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='unique_user_meal_slot_name'),
        ),
        migrations.AddConstraint(
            model_name='nutritiongoal',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='unique_open_nutrition_goal_per_user'),
        ),
        migrations.AddConstraint(
            model_name='nutritiontarget',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='unique_open_nutrition_target_per_user'),
        ),
        migrations.AddConstraint(
            model_name='dietplanitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('food__isnull', False), ('recipe__isnull', True)), models.Q(('food__isnull', True), ('recipe__isnull', False)), _connector='OR'), name='diet_plan_item_exactly_one_of_food_or_recipe'),
        ),
        migrations.AddConstraint(
            model_name='diaryentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('food__isnull', False), ('recipe__isnull', True)), models.Q(('food__isnull', True), ('recipe__isnull', False)), _connector='OR'), name='diary_entry_exactly_one_of_food_or_recipe'),
        ),
    ]
