# Generated by Django 6.1 on 2026-08-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_seed_meal_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritiontarget',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='nutrition.nutritiongoal'),
        ),
    ]
