# Generated by Django 6.1 on 2026-08-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_nutritiontarget_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenFoodFactsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='off_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='food',
            name='off_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='nutrition.food'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='meal_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nutrition.mealslot'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='nutrition.recipe'),
        ),
        migrations.AlterField(
            model_name='dietplanitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nutrition.food'),
        ),
        migrations.AlterField(
            model_name='dietplanitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nutrition.recipe'),
        ),
        migrations.AlterField(
            model_name='dietplanmeal',
            name='meal_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nutrition.mealslot'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nutrition.food'),
        ),
    ]
