# Generated by Django 6.1 on 2026-08-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_openfoodfactssettings_food_off_id_food_off_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='nova_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — unprocessed or minimally processed'), (2, '2 — processed culinary ingredients'), (3, '3 — processed food'), (4, '4 — ultra-processed food')], null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='nutri_score',
            field=models.CharField(blank=True, choices=[('a', 'A — best'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E — worst')], max_length=1, null=True),
        ),
    ]
