# Generated by Django 6.1 on 2026-08-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_food_nova_group_food_nutri_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiontarget',
            name='calorie_floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='capped_rate_kg_per_week',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='floor_was_applied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='rate_cap_fraction_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='rate_was_capped',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='raw_calories_before_floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='tdee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
