# Generated by Django 6.1 on 2026-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_seed_template_recipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietplanmeal',
            options={'ordering': ['weekday', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='dietplan',
            name='is_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietplanmeal',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
