# Generated by Django 6.1 on 2026-08-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_dietplan_unique_active_diet_plan_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nutrition.mealslot'),
        ),
    ]
