# Generated by Django 6.1.1 on 2026-09-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_add_more_default_meal_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='categories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
