# Generated by Django 6.1.1 on 2026-09-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_food_categories_food_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='allergens',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='food',
            name='labels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
