# Generated by Django 6.1.1 on 2026-09-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_food_allergens_food_ingredients_text_food_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='food',
            name='price_sample_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='price_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
