# Generated by Django 6.1.1 on 2026-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0016_food_price_amount_food_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_thumb_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
