# Generated by Django 6.1.1 on 2026-09-20 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0018_dietplan_coach_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='shared_with_clients',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='shared_with_clients',
            field=models.ManyToManyField(blank=True, related_name='shared_diet_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
