# Generated by Django 6.1.1 on 2026-09-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0019_remove_dietplan_shared_with_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openfoodfactssettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
