# Generated by Django 6.1.1 on 2026-10-01 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0020_openfoodfactssettings_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diaryentry',
            name='diary_entry_exactly_one_of_food_or_recipe',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='quick_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='quick_carbohydrate_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='quick_fat_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='quick_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='quick_protein_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='diaryentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('food__isnull', False), ('quick_calories__isnull', True), ('recipe__isnull', True)), models.Q(('food__isnull', True), ('quick_calories__isnull', True), ('recipe__isnull', False)), models.Q(('food__isnull', True), ('quick_calories__isnull', False), ('recipe__isnull', True)), _connector='OR'), name='diary_entry_exactly_one_of_food_recipe_or_quick'),
        ),
    ]
