# Generated by Django 6.1.1 on 2026-10-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0021_diaryentry_quick_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='energy_kj',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='other_nutrients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='food',
            name='polyols_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='salt_grams',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='starch_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
