# Generated by Django 6.1.1 on 2026-10-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0023_recipe_meal_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='shopping_includes_shopping_day',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ShoppingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_days', to='nutrition.dietplan')),
            ],
            options={
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('diet_plan', 'weekday'), name='unique_shopping_day_per_plan'), models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='shopping_day_is_a_weekday')],
            },
        ),
    ]
