# Generated by Django 6.1 on 2026-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedbacksettings_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_engine_indexing_enabled', models.BooleanField(default=False, help_text='Lets search engines crawl and index this instance. Off by default — most installs are a private, self-hosted app for one household, not a public site anyone should be searching for.')),
            ],
        ),
    ]
