# Generated by Django 6.1.1 on 2026-09-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncedVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
    ]
