# Generated by Django 6.1 on 2026-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcedversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('workouts', 'Workouts'), ('programs', 'Programs'), ('progress', 'Progress'), ('measurements', 'Body measurements'), ('activities', 'Activities'), ('nutrition', 'Nutrition'), ('stretching', 'Stretching'), ('account', 'Account & profile'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
