# Generated by Django 5.0.14 on 2026-08-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_seed_exercise_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exercises.equipment', verbose_name='equipment'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='movement_type',
            field=models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation')], default='compound', max_length=20, verbose_name='movement type'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='primary_exercises', to='exercises.musclegroup', verbose_name='primary muscle groups'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.musclegroup', verbose_name='secondary muscle groups'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_input_mode',
            field=models.CharField(choices=[('total', 'Total load'), ('per_hand', 'Per hand / dumbbell')], default='total', max_length=20, verbose_name='weight logging'),
        ),
    ]
