# Generated by Django 6.1 on 2026-09-13 00:46

import apps.exercises.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_seed_more_muscle_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_images_per_exercise', models.PositiveSmallIntegerField(default=5, help_text='How many images a single exercise may hold at once. Applies to every exercise, system and custom alike.', validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.exercises.models.exercise_image_upload_to, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('attribution', models.CharField(blank=True, max_length=200, verbose_name='attribution')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exercises.exercise')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
