# Generated by Django 6.1.1 on 2026-09-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_seed_exercise_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='instructions'),
        ),
    ]
