# Generated by Django 6.1.1 on 2026-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_exercise_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions_attribution',
            field=models.CharField(blank=True, max_length=200, verbose_name='instructions attribution'),
        ),
    ]
