# Generated by Django 5.0.14 on 2026-08-13 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_seed_exercise_library'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(choices=[('max_weight', 'Max weight'), ('rep_pr', 'Rep PR'), ('rep_specific_pr', 'Rep-specific PR'), ('estimated_1rm', 'Estimated 1RM'), ('set_volume', 'Set volume'), ('session_volume', 'Session volume')], max_length=20)),
                ('rep_count', models.PositiveIntegerField(blank=True, help_text="The N in 'NRM' — only set for rep_specific_pr.", null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.PositiveIntegerField()),
                ('achieved_at', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_records', to='exercises.exercise')),
                ('source_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_achieved', to='workouts.exerciseset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
    ]
