# Generated by Django 5.0.14 on 2026-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalrecord',
            name='achieved_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
