# Generated by Django 5.0.14 on 2026-08-13 12:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_seed_exercise_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False, help_text='Available to be copied rather than run directly.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(blank=True, help_text='Null for built-in system templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scheduled_weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='programs.program')),
            ],
            options={
                'ordering': ['program_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExercisePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('set_count', models.PositiveIntegerField(default=3)),
                ('min_reps', models.PositiveIntegerField(default=8)),
                ('max_reps', models.PositiveIntegerField(default=12)),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('target_rir', models.PositiveIntegerField(blank=True, null=True)),
                ('progression_method', models.CharField(choices=[('double_progression', 'Double progression'), ('linear', 'Linear'), ('percentage_based', 'Percentage based'), ('rpe_rir', 'RPE/RIR based'), ('rep_range', 'Rep range'), ('maintenance', 'Maintenance'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('weight_increment', models.DecimalField(blank=True, decimal_places=2, default=Decimal('2.5'), max_digits=6, null=True)),
                ('percentage_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='programs.workout')),
            ],
            options={
                'ordering': ['workout_id', 'order', 'id'],
            },
        ),
    ]
