# Generated by Django 5.0.14 on 2026-08-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_seed_program_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprescription',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Canonical kg. What a workout session snapshots as its starting target — set manually for now; a future progression engine (Phase 6) may update it between cycles.', max_digits=6, null=True),
        ),
    ]
