# Generated by Django 5.0.14 on 2026-08-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_seed_more_program_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprescription',
            name='max_reps',
            field=models.PositiveIntegerField(default=12, verbose_name='maximum reps'),
        ),
        migrations.AlterField(
            model_name='exerciseprescription',
            name='min_reps',
            field=models.PositiveIntegerField(default=8, verbose_name='minimum reps'),
        ),
        migrations.AlterField(
            model_name='exerciseprescription',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='exerciseprescription',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='exerciseprescription',
            name='set_count',
            field=models.PositiveIntegerField(default=3, verbose_name='set count'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='scheduled_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, verbose_name='scheduled weekday'),
        ),
    ]
