# Generated by Django 6.1.1 on 2026-09-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_seed_more_program_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='coach_snapshot',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='coach_snapshot_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='imported_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_copies', to='programs.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='shared_with_clients',
            field=models.BooleanField(default=False),
        ),
    ]
