# Generated by Django 6.1.1 on 2026-10-02 19:16

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'You'), ('assistant', 'Assistant')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('running', 'Writing'), ('done', 'Done'), ('error', 'Failed')], db_index=True, default='done', max_length=10)),
                ('text', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=list)),
                ('activity', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', apps.accounts.models.EncryptedTextField(blank=True, default='', key_setting='ASSISTANT_ENCRYPTION_KEY')),
                ('api_key_hint', models.CharField(blank=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('diet_plan', 'Diet plan'), ('program', 'Workout program')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Waiting for you'), ('accepted', 'Created'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='assistant.assistantmessage')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text="Turns the assistant off for everyone, including users' own keys.")),
                ('shared_key_access', models.CharField(choices=[('nobody', 'Nobody — users must bring their own key'), ('staff', 'Staff only'), ('selected', 'Selected users'), ('everyone', 'Everyone')], default='staff', help_text="Who may use this instance's own provider (ASSISTANT_API_KEY, or the Ollama server). Its usage is billed to you, the operator.", max_length=10)),
                ('daily_token_limit', models.PositiveIntegerField(default=200000, help_text="Tokens (input + output) one user may spend per day on the shared provider. 0 means no limit. Users' own keys are never limited.")),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Used when access is set to “Selected users”.', related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('key_source', models.CharField(choices=[('shared', "This instance's provider"), ('own', 'Your own API key')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation'),
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('key_source', models.CharField(choices=[('shared', "This instance's provider"), ('own', 'Your own API key')], max_length=10)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'key_source'), name='unique_assistant_usage_per_day')],
            },
        ),
    ]
