# Generated by Django 6.1.1 on 2026-10-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_assistantpreference_own_key_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantpreference',
            name='own_key_effort',
            field=models.CharField(blank=True, choices=[('low', 'Low — quickest and cheapest; fine for everyday questions'), ('medium', 'Medium — balanced'), ('high', 'High — more thorough plans, more tokens'), ('xhigh', 'Extra high — for demanding planning'), ('max', 'Maximum — the most thorough and the most expensive')], max_length=10),
        ),
    ]
