# Generated by Django 6.1 on 2026-09-23 14:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0010_seed_exercise_instructions'),
        ('workouts', '0003_resttimernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=10, verbose_name='type')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('default_hold_seconds', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='default hold (seconds)')),
                ('per_side', models.BooleanField(default=False, help_text='Held once for the left side and once for the right.', verbose_name='one side at a time')),
                ('muscle_groups', models.ManyToManyField(blank=True, related_name='stretches', to='exercises.musclegroup', verbose_name='muscle groups')),
                ('owner', models.ForeignKey(blank=True, help_text='Null for built-in system stretches.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_stretches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stretches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StretchRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null for built-in system routines.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stretch_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hold_seconds', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='hold (seconds)')),
                ('sets', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='sets')),
                ('rest_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(300)], verbose_name='rest between holds (seconds)')),
                ('stretch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_items', to='stretching.stretch')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stretching.stretchroutine')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StretchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='date')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('after_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooldown_stretch_sessions', to='workouts.workoutsession')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stretching.stretchroutine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stretch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformedStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('stretch_name', models.CharField(max_length=100)),
                ('per_side', models.BooleanField(default=False)),
                ('target_hold_seconds', models.PositiveIntegerField()),
                ('sets', models.PositiveSmallIntegerField(default=1)),
                ('rest_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('actual_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('stretch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stretching.stretch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_stretches', to='stretching.stretchsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stretch',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='unique_system_stretch_name'),
        ),
        migrations.AddConstraint(
            model_name='stretch',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='unique_user_stretch_name'),
        ),
        migrations.AddConstraint(
            model_name='stretchroutine',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='unique_system_stretch_routine_name'),
        ),
        migrations.AddConstraint(
            model_name='stretchroutine',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='unique_user_stretch_routine_name'),
        ),
        migrations.AddConstraint(
            model_name='stretchsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user',), name='one_in_progress_stretch_session_per_user'),
        ),
    ]
