# Generated by Django 5.0.14 on 2026-08-13 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_kind', models.CharField(choices=[('weight', 'Weight'), ('length', 'Length/circumference'), ('percentage', 'Percentage')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null for built-in system measurement types.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_measurement_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=8)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to=settings.AUTH_USER_MODEL)),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measurements.measurementtype')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='measurementtype',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='unique_system_measurement_type_name'),
        ),
        migrations.AddConstraint(
            model_name='measurementtype',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='unique_user_measurement_type_name'),
        ),
    ]
