# Generated by Django 5.0.14 on 2026-08-13 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_seed_measurement_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
