# Generated by Django 5.0.14 on 2026-08-13 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_bodymeasurement_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='recorded at'),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='unit_kind',
            field=models.CharField(choices=[('weight', 'Weight'), ('length', 'Length/circumference'), ('percentage', 'Percentage')], max_length=20, verbose_name='unit kind'),
        ),
    ]
