# Generated by Django 5.0.14 on 2026-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_seed_activity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
