# Generated by Django 5.0.14 on 2026-08-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(db_index=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distance'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
