# Generated by Django 6.1 on 2026-08-27 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
